apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo
  region: us-east-1
  version: "1.19"
# iam:
#     withOIDC: true
#     serviceAccounts:
#     - metadata:
#         name: s3-reader
#       attachPolicyARNs:
#       - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
availabilityZones: [ 'us-east-1a', 'us-east-1b' ]
nodeGroups:
  - name: poolDefault
    instanceType: t3.medium
    desiredCapacity: 3
    #iam:
      #withAddonPolicies:
        #albIngress: true
