name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger app deployment
      uses: statsig-io/kubectl-via-eksctl@main
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-1
        cluster: ${{ secrets.CLUSTER }}
      with:
        args: rollout restart deployment/willanyoneeverreadthis
