name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: kubectl via eksctl
      uses: statsig-io/kubectl-via-eksctl@v1.18.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

